services:
  web:
    build:
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  app:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: lgtmofumofu
      DB_PASSWORD: lgtmofumofu
      DB_NAME: lgtmofumofu

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: lgtmofumofu
      MYSQL_DATABASE: lgtmofumofu
      MYSQL_USER: lgtmofumofu
      MYSQL_PASSWORD: lgtmofumofu
    ports:
      - "3306:3306"
